# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bbspost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=50)),
                ('uid', models.IntegerField()),
                ('content', models.TextField()),
                ('secid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bbsuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('isadmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('comment', models.TextField()),
                ('postid', models.IntegerField()),
                ('pcid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secname', models.CharField(max_length=50)),
                ('detail', models.TextField()),
            ],
        ),
    ]
